server {
    listen 80;
    server_name romagram.kz www.romagram.kz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name romagram.kz www.romagram.kz;
    client_max_body_size 50M;

    # SSL сертификаты (пути внутри контейнера Nginx)
    ssl_certificate     /etc/letsencrypt/live/romagram.kz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/romagram.kz/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/romagram.kz/chain.pem;

    # Оптимизация TLS
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers off;

    # HTTP → HTTPS Strict
    add_header Strict-Transport-Security "max-age=63072000" always;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    location /ws/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_read_timeout 60m;
    }

    location /media/ {
        alias /django/media/;   # путь в контейнере до MEDIA_ROOT
    }
}
